# Generated by Django 5.0.2 on 2024-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(default='luhdev', max_length=6, unique=True)),
                ('url_youtube_admin', models.URLField(default='https://youtube.com')),
                ('url_instagram_admin', models.URLField(default='https://www.instagram.com/works_manager')),
                ('url_github_admin', models.URLField(default='https://github.com/Kamado8421/')),
            ],
        ),
    ]
