# Generated by Django 5.0.2 on 2024-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_configbot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infos',
            new_name='Info',
        ),
    ]
