# Generated by Django 5.0.2 on 2024-06-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('bonus', models.IntegerField()),
                ('minLevel', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=35, unique=True)),
                ('nome', models.CharField(max_length=35)),
                ('saldo', models.FloatField(default=0)),
                ('debito', models.FloatField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ranks')),
            ],
        ),
    ]
