# Generated by Django 5.0.2 on 2024-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranks',
            new_name='Rank',
        ),
    ]
