# Generated by Django 5.0.2 on 2024-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banido',
            field=models.BooleanField(blank=None, default=False, null=None),
        ),
    ]
