# Generated by Django 5.0.2 on 2024-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_usuario_banido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='banido',
            field=models.BooleanField(default=False),
        ),
    ]
